<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HuPan-PC" ignored="0" name="点菜结账流程" tests="1" failures="1" timestamp="26 十月 2017 10:12:13 GMT" time="41.637" errors="0">
  <testcase name="Start" time="40.333" classname="com.testng.SettleAccounts">
    <failure type="java.lang.AssertionError" message="找不到开台成功">
      <![CDATA[java.lang.AssertionError: 找不到开台成功
	at com.common.Utils.findToast(Utils.java:1733)
	at com.testng.SettleAccounts.Start(SettleAccounts.java:61)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Start -->
</testsuite> <!-- 点菜结账流程 -->
